<a href="https://colab.research.google.com/github/kimdonggyufive/OpenReposit/blob/main/2_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#현재 작업하고있는 페이지
!pwd

/content


In [4]:
#현재 작업 목록을 보여준다
!ls

sample_data


In [7]:
#Colab에는 이미 numpy이가 설치되어있음.
pip install numpy

In [8]:
import numpy as np


In [12]:
[i for i in range(7)]
  

[0, 1, 2, 3, 4, 5, 6]

In [16]:
[i for i in range(7)]

[0, 1, 2, 3, 4, 5, 6]

In [17]:
{i: i+2 for i in range(7)}

{0: 2, 1: 3, 2: 4, 3: 5, 4: 6, 5: 7, 6: 8}

In [18]:
#
{i:np.random.randn() for i in range(7)}

{0: -0.30538563119434714,
 1: 1.7086543735962085,
 2: -0.8045216773308729,
 3: 0.19412479176260883,
 4: -2.6433938570580415,
 5: -0.9256111339851438,
 6: 0.04609086620831801}

In [22]:
a=np.array([1,2,3])
a,type(a)
a.ndim, a.shape

(1, (3,))

In [23]:
a[0],a[1],a[2]

(1, 2, 3)

In [27]:
a[:2],a[:3],a[:],a[0:],a[1:2]

(array([1, 2]),
 array([1, 2, 3]),
 array([1, 2, 3]),
 array([1, 2, 3]),
 array([2]))

In [30]:
a[-1:2],a[-1:-2],a[-1:-3],a[0:-2]

(array([], dtype=int64),
 array([], dtype=int64),
 array([], dtype=int64),
 array([1]))

In [31]:
pip install conda

     |████████████████████████████████| 299 kB 8.6 MB/s 
     |████████████████████████████████| 66 kB 4.0 MB/s 
     |████████████████████████████████| 109 kB 46.2 MB/s 
     |████████████████████████████████| 546 kB 38.8 MB/s 
  Created wheel for conda: filename=conda-4.3.16-py3-none-any.whl size=336960 sha256=8ef15e6ddc0a945d56dc3874469a7c20004d3ed9201016a4c5d57cca552f8f8d
  Stored in directory: /root/.cache/pip/wheels/66/ec/2c/cce33d7a071720882d948fd3364d3ff5562bac9e5638768d41
  Created wheel for pycosat: filename=pycosat-0.6.3-cp37-cp37m-linux_x86_64.whl size=143866 sha256=194e00289f969de02dba99fdf4aa83e57f96b109429341bccd993b9dc8865ed1
  Stored in directory: /root/.cache/pip/wheels/c8/29/0e/a226b7c5a4f24e246f25201c0b1fbf6fb8f19f9cce89b02c36
Successfully built conda pycosat


In [35]:
a=np.array([[1,2,3],
          [4,5,6]])

a

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
#shell에서는 0번째 인자는 가로, 1번째 인자는 세로를 뜻한다.


In [41]:
a=np.array([[1,2,3], [4,5,6]])

a[0][1],a[0][-3],a[0][-2],a[0][-1]

(2, 1, 2, 3)

In [43]:
a[0:2][0:3]

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
a[:,:-1]

array([[1, 2],
       [4, 5]])

In [48]:
a= np.arange(32)

a, type(a), a.ndim, a.shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]),
 numpy.ndarray,
 1,
 (32,))

In [52]:
a= np.arange(32).reshape(-1,16)

a, type(a), a.ndim, a.shape

(array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]]),
 numpy.ndarray,
 2,
 (2, 16))

In [57]:
a= np.arange(32).reshape(2,4,1,4,1)

a

array([[[[[ 0],
          [ 1],
          [ 2],
          [ 3]]],


        [[[ 4],
          [ 5],
          [ 6],
          [ 7]]],


        [[[ 8],
          [ 9],
          [10],
          [11]]],


        [[[12],
          [13],
          [14],
          [15]]]],



       [[[[16],
          [17],
          [18],
          [19]]],


        [[[20],
          [21],
          [22],
          [23]]],


        [[[24],
          [25],
          [26],
          [27]]],


        [[[28],
          [29],
          [30],
          [31]]]]])

In [59]:
a=np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [61]:
a=np.zeros(2)
a

array([0., 0.])

In [64]:
a=np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [69]:
a=np.random.random()
a

0.747483076845841

In [77]:
#np.random.seed(777)
a=np.random.random((2,3))
a


array([[0.58961375, 0.34334054, 0.98887615],
       [0.62647321, 0.68177928, 0.55225681]])

In [80]:
a=np.array([[1,2,3,4],[5,6,7,8,],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [82]:
b=a[:2,1:3]
b

array([[2, 3],
       [6, 7]])

In [84]:
a=np.array([[1,2,3,4],[5,6,7,8,],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [86]:
#1차원 배열
col_r1=a[:1]
col_r1

array([[1, 2, 3, 4]])

In [88]:
#2차원 배열
col_r2=a[:2]
col_r2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [121]:
a=np.array([[1,2],[3,4],[5,6]])

a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [92]:
a[0,1],a[0,1]

(2, 2)

In [94]:
a[[0,0],[1,1]]

array([2, 2])

In [126]:
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [127]:
b=np.array([0,2,0,1])
b

array([0, 2, 0, 1])

In [128]:
c=np.arange(4)
c

array([0, 1, 2, 3])

In [105]:
#원하는 픽셀을 뽑을 수 있도록 하는 함수.
#두개는 같은 함수
a[c,b], a[[0,1,2,3],[0,2,0,1]]

(array([ 1,  6,  7, 11]), array([ 1,  6,  7, 11]))

In [115]:
d=np.array([1,6,7,11])
d

array([ 1,  6,  7, 11])

In [117]:
#모든 항에 사칙연산을 해준다.
d=d-10
d

array([-19, -14, -13,  -9])

In [141]:
a[c,b]+=10

a

array([[31,  2,  3],
       [ 4,  5, 36],
       [37,  8,  9],
       [10, 41, 12]])

In [145]:
a=np.array([[1,2,3],
           [4,5,6],
           [7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [133]:
#다음은 값이 false인지 true인지 확인하는 함수

a>10

array([[ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [False,  True,  True]])

In [137]:
a[np.array([[ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [False,  True,  True]])]
a

array([[21,  2,  3],
       [ 4,  5, 26],
       [27,  8,  9],
       [10, 31, 12]])

In [147]:
#원하는 값들만 뽑아내는 방법.
a[a>2]

array([3, 4, 5, 6, 7, 8, 9])

In [149]:
#정수형을 실수형으로 바꾸는 방법
a=np.array([1,2], dtype=np.float64)

a, a.dtype

(array([1., 2.]), dtype('float64'))

In [151]:
#int형으로 변환
a=a.astype('int64')
a

array([1, 2])

In [152]:
import numpy as np


In [157]:
x=np.array([[1.0,2.0],
            [3.0,4.0]])
y=np.array([[5.0,6.0],
            [7.0,8.0]])

In [158]:
#행렬의 곱셈 공식
x@y

array([[19., 22.],
       [43., 50.]])